version: "3.7"

volumes:
  db-data:
    driver: local
  public-storage:
    driver: local

networks:
  gallery:
    driver: bridge

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: app_server
    container_name: gallery-app
    restart: unless-stopped
    working_dir: /var/www/
    env_file:
      - .env
    networks:
      - gallery
    volumes:
      - public-storage:/var/www/storage/app/public
  db:
    image: mysql:5.7
    container_name: gallery-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - gallery
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: web_server
    container_name: gallery-web
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - gallery
    volumes:
      - public-storage:/var/www/public/storage:ro
